apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devOps-app
  template:
    metadata:
      labels:
        app: devOps-app
    spec:
      containers:
      - name: devOps-app-container
        image: nginx:latest   # Utilisation de l'image nginx
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_HOST
            value: database-service  # Nom du service de la base de données dans le cluster
          - name: DATABASE_PORT
            value: "3306"  # Port de la base de données
          - name: DATABASE_USER
            value: dbuser
          - name: DATABASE_PASSWORD
            value: dbpassword
          - name: DATABASE_NAME
            value: mydatabase

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: devOps-app
  ports:
    - protocol: TCP
      port: 80  # Port externe auquel le service sera exposé
      targetPort: 8080  # Port auquel les pods répondent
  type: LoadBalancer